export const BASEROW_TABLES = {
  users: 'users',
  tenants: 'tenants',
  auditLogs: 'audit_logs',
} as const;

export const TENANT_TABLE_BASES = [
  'clients',
  'gestionnaires',
  'kyc_documents',
  'notes',
  'relations',
  'tasks',
  'audit_logs',
  'fcc_clients',
] as const;

export const BASEROW_FIELDS = {
  users: {
    email: 'email',
    passwordHash: 'password_hash',
    name: 'Name',
    role: 'role',
    tenantId: 'tenant_id',
    status: 'status',
    resetTokenHash: 'reset_token_hash',
    resetTokenExpires: 'reset_token_expires',
    otpHash: 'otp_hash',
    otpExpires: 'otp_expires',
    otpAttempts: 'otp_attempts',
    createdOn: 'created_on',
    updatedOn: 'updated_on',
    airtableRecordId: 'airtable_record_id',
  },
  tenants: {
    name: 'Name',
    slug: 'slug',
    status: 'status',
    databaseId: 'database_id',
    workspaceId: 'workspace_id',
    databaseToken: 'database_token',
    brandingName: 'branding_name',
    brandingOrias: 'branding_orias',
    brandingAccent: 'branding_accent',
    brandingLogo: 'branding_logo',
    email: 'email',
    backofficeEmail: 'backoffice_email',
    createdOn: 'created_on',
    updatedOn: 'updated_on',
    // Per-tenant Microsoft 365 / SharePoint OAuth connection.
    // Tokens are AES-256-GCM ciphertext at rest — see src/utils/crypto.ts.
    sharepointConnected: 'sharepoint_connected',
    sharepointAccessToken: 'sharepoint_access_token',
    sharepointRefreshToken: 'sharepoint_refresh_token',
    sharepointTokenExpiresAt: 'sharepoint_token_expires_at',
    sharepointMsTenantId: 'sharepoint_ms_tenant_id',
    sharepointSiteId: 'sharepoint_site_id',
    sharepointDriveId: 'sharepoint_drive_id',
    sharepointSiteDisplayName: 'sharepoint_site_display_name',
    sharepointConnectedAt: 'sharepoint_connected_at',
    sharepointConnectedBy: 'sharepoint_connected_by',
    // Per-tenant transactional email OAuth (Microsoft 365 Mail.Send OR Gmail).
    // Independent of the SharePoint connection above — a tenant may use Gmail for
    // email and Microsoft for SharePoint. Tokens are AES-256-GCM ciphertext at
    // rest — see src/utils/crypto.ts.
    emailProvider: 'email_provider', // 'microsoft' | 'google' | ''
    emailAccessToken: 'email_access_token',
    emailRefreshToken: 'email_refresh_token',
    emailTokenExpiresAt: 'email_token_expires_at',
    emailMsTenantId: 'email_ms_tenant_id',
    emailSenderAddress: 'email_sender_address',
    emailScopesGranted: 'email_scopes_granted',
    emailConnectedAt: 'email_connected_at',
    emailConnectedBy: 'email_connected_by',
  },
  clients: {
    name: 'Name',
    email: 'email',
    clientType: 'client_type',
    kycStatus: 'kyc_status',
    status: 'status',
    statutClient: 'statut_client',
    signataire: 'signataire',
    gestionnaire: 'gestionnaire',
    origine: 'origine',
    dateEntree: 'date_entree',
    phone: 'phone',
    phoneMobile: 'phone_mobile',
    phoneHome: 'phone_home',
    phoneOffice: 'phone_office',
    address: 'address',
    postalCode: 'postal_code',
    city: 'city',
    country: 'country',
    civilite: 'civilite',
    firstName: 'first_name',
    lastName: 'last_name',
    birthDate: 'birth_date',
    birthPlace: 'birth_place',
    nationality: 'nationality',
    maritalStatus: 'marital_status',
    matrimonialRegime: 'matrimonial_regime',
    profession: 'profession',
    proStatus: 'pro_status',
    sector: 'sector',
    employer: 'employer',
    annualIncome: 'annual_income',
    currentCharges: 'current_charges',
    tradeName: 'trade_name',
    legalForm: 'legal_form',
    siren: 'siren',
    nafCode: 'naf_code',
    activity: 'activity',
    legalRepName: 'legal_rep_name',
    legalRepRole: 'legal_rep_role',
    revenue: 'revenue',
    totalBalance: 'total_balance',
    equity: 'equity',
    taxation: 'taxation',
    fiscalCountry: 'fiscal_country',
    capital: 'capital',
    patrimoineImmobilier: 'patrimoine_immobilier',
    patrimoineEpargne: 'patrimoine_epargne',
    patrimoineParticipations: 'patrimoine_participations',
    patrimoineLiquidites: 'patrimoine_liquidites',
    patrimoineAutres: 'patrimoine_autres',
    fccStatut: 'fcc_statut',
    fccDate: 'fcc_date',
    derStatut: 'der_statut',
    derDate: 'der_date',
    derEnvoiTimestamp: 'der_envoi_timestamp',
    ldmStatut: 'ldm_statut',
    ldmDate: 'ldm_date',
    notesInternes: 'notes_internes',
    airtableRecordId: 'airtable_record_id',
    be1Nom: 'be1_nom',
    be1Ddn: 'be1_ddn',
    be1LieuNaissance: 'be1_lieu_naissance',
    be1Nationalite: 'be1_nationalite',
    be1Adresse: 'be1_adresse',
    be1ResidenceFiscale: 'be1_residence_fiscale',
    be1Detention: 'be1_detention',
    be2Nom: 'be2_nom',
    be2Ddn: 'be2_ddn',
    be2LieuNaissance: 'be2_lieu_naissance',
    be2Nationalite: 'be2_nationalite',
    be2Adresse: 'be2_adresse',
    be2ResidenceFiscale: 'be2_residence_fiscale',
    be2Detention: 'be2_detention',
    be3Nom: 'be3_nom',
    be3Ddn: 'be3_ddn',
    be3LieuNaissance: 'be3_lieu_naissance',
    be3Nationalite: 'be3_nationalite',
    be3Adresse: 'be3_adresse',
    be3ResidenceFiscale: 'be3_residence_fiscale',
    be3Detention: 'be3_detention',
    be4Nom: 'be4_nom',
    be4Ddn: 'be4_ddn',
    be4LieuNaissance: 'be4_lieu_naissance',
    be4Nationalite: 'be4_nationalite',
    be4Adresse: 'be4_adresse',
    be4ResidenceFiscale: 'be4_residence_fiscale',
    be4Detention: 'be4_detention',
  },
  gestionnaires: {
    name: 'Name',
    firstName: 'first_name',
    lastName: 'last_name',
    email: 'email',
    phone: 'phone',
    role: 'role',
    peutSignerDocusign: 'peut_signer_docusign',
    status: 'status',
    initiales: 'initiales',
    couleur: 'couleur',
    userId: 'user_id',
    airtableRecordId: 'airtable_record_id',
  },
  kycDocuments: {
    name: 'Name',
    clientId: 'client_id',
    clientIdOld: 'client_id_old',
    clientNom: 'client_nom',
    docType: 'doc_type',
    recu: 'recu',
    dateReception: 'date_reception',
    dateValidite: 'date_validite',
    urlDocument: 'url_document',
    airtableRecordId: 'airtable_record_id',
  },
  notes: {
    name: 'Name',
    clientId: 'client_id',
    date: 'date',
    noteType: 'note_type',
    auteur: 'auteur',
    contenu: 'contenu',
    piecesJointes: 'pieces_jointes',
    source: 'source',
    airtableRecordId: 'airtable_record_id',
  },
  relations: {
    name: 'Name',
    clientAId: 'client_a_id',
    clientBId: 'client_b_id',
    typeRelation: 'type_relation',
    pctDetention: 'pct_detention',
    note: 'note',
    airtableRecordId: 'airtable_record_id',
  },
  tasks: {
    name: 'Name',
    title: 'title',
    description: 'description',
    status: 'status',
    priorite: 'priorite',
    assigneA: 'assigne_a',
    creePar: 'cree_par',
    dueDate: 'due_date',
    clientId: 'client_id',
    airtableRecordId: 'airtable_record_id',
  },
  auditLogs: {
    name: 'Name',
    createdAt: 'created_at',
    userId: 'user_id',
    userEmail: 'user_email',
    userName: 'user_name',
    userRole: 'user_role',
    tenantId: 'tenant_id',
    action: 'action',
    method: 'method',
    path: 'path',
    statusCode: 'status_code',
    entityType: 'entity_type',
    entityId: 'entity_id',
    details: 'details',
  },
  fccClients: {
    name: 'Name',
    clientId: 'client_id',
    profilRisque: 'Profil_Risque',
    profilConnaissance: 'Profil_Connaissance',
    scoreConnaissance: 'Score_Connaissance',
    scoreRisque: 'Score_Risque',
    docusignEnvelopeId: 'DocuSign_Envelope_ID',
    docusignSentAt: 'DocuSign_Sent_At',
    notesNm: 'Notes_NM',
    migrationRecordId: 'migration_record_id',
    typeFormulaire: 'Type_Formulaire',
    idFormulaire: 'ID_Formulaire',
    dateSoumission: 'Date_Soumission',
    statutDossier: 'Statut_Dossier',
    client: 'Client',
    email: 'Email',
    telephone: 'Telephone',
    ville: 'Ville',
    profession: 'Profession',
    scoreTotal: 'Score_Total',
    sharepointFileUrl: 'SharePoint_File_URL',
    sharepointFileId: 'SharePoint_File_ID',
    ipClient: 'IP_Client',
    pdfFilename: 'pdf_filename',
    prefillToken: 'prefill_token',
    boAgent: 'bo_agent',
    be1Nom: 'be1_nom',
    be1Ddn: 'be1_ddn',
    be1LieuNaissance: 'be1_lieu_naissance',
    be1Nationalite: 'be1_nationalite',
    be1ResidenceFiscale: 'be1_residence_fiscale',
    be1Adresse: 'be1_adresse',
    be1Detention: 'be1_detention',
    be2Nom: 'be2_nom',
    be2Ddn: 'be2_ddn',
    be2LieuNaissance: 'be2_lieu_naissance',
    be2Nationalite: 'be2_nationalite',
    be2ResidenceFiscale: 'be2_residence_fiscale',
    be2Adresse: 'be2_adresse',
    be2Detention: 'be2_detention',
    be3Nom: 'be3_nom',
    be3Ddn: 'be3_ddn',
    be3Nationalite: 'be3_nationalite',
    be3Detention: 'be3_detention',
    be4Nom: 'be4_nom',
    be4Ddn: 'be4_ddn',
    be4Nationalite: 'be4_nationalite',
    be4Detention: 'be4_detention',
    clientDenomination: 'client_denomination',
    clientRepresentantNom: 'client_representant_nom',
    clientRepresentantFonction: 'client_representant_fonction',
    clientSiren: 'client_siren',
    clientNaf: 'client_naf',
    clientActivite: 'client_activite',
    clientFormeJuridique: 'client_forme_juridique',
    clientCa: 'client_ca',
    clientBilan: 'client_bilan',
    clientFondsPropres: 'client_fonds_propres',
    clientFiscalite: 'client_fiscalite',
  },
} as const;

export const TENANT_STATUS_OPTIONS = [
  { value: 'active', color: 'dark-green' },
  { value: 'inactive', color: 'dark-orange' },
  { value: 'provisioning', color: 'dark-blue' },
  { value: 'failed', color: 'dark-red' },
] as const;

export const USER_STATUS_OPTIONS = [
  { value: 'active', color: 'dark-green' },
  { value: 'inactive', color: 'dark-orange' },
  { value: 'pending', color: 'dark-yellow' },
] as const;

export const USER_ROLE_OPTIONS = [
  { value: 'super_admin', color: 'dark-blue' },
  { value: 'tenant_admin', color: 'dark-purple' },
  { value: 'standard_user', color: 'dark-gray' },
] as const;

export const KYC_STATUS_OPTIONS = [
  { value: 'pending', color: 'dark-orange' },
  { value: 'in_progress', color: 'dark-blue' },
  { value: 'complete', color: 'dark-green' },
  { value: 'rejected', color: 'dark-red' },
] as const;

export const CLIENT_TYPE_OPTIONS = [
  { value: 'PP', color: 'dark-blue' },
  { value: 'PM', color: 'dark-purple' },
] as const;

export const CLIENT_STATUS_OPTIONS = [
  { value: 'active', color: 'dark-green' },
  { value: 'inactive', color: 'dark-orange' },
  { value: 'prospect', color: 'dark-blue' },
  { value: 'archived', color: 'dark-gray' },
] as const;

export const STATUT_CLIENT_OPTIONS = [
  { value: 'Prospect', color: 'dark-blue' },
  { value: 'En cours', color: 'dark-orange' },
  { value: 'Client actif', color: 'dark-green' },
  { value: 'Inactif', color: 'dark-gray' },
  { value: 'Archivé', color: 'dark-gray' },
] as const;

export const CRM_DOC_STATUS_OPTIONS = [
  { value: 'Non envoyé', color: 'dark-gray' },
  { value: 'Envoyé', color: 'dark-blue' },
  { value: 'DocuSign envoyé', color: 'dark-purple' },
  { value: 'Signé', color: 'dark-green' },
  { value: 'À renouveler', color: 'dark-orange' },
] as const;

export const TASK_STATUS_OPTIONS = [
  { value: 'À faire', color: 'dark-blue' },
  { value: 'En cours', color: 'dark-orange' },
  { value: 'Fait', color: 'dark-green' },
  { value: 'Reporté', color: 'dark-gray' },
] as const;

export const TASK_PRIORITE_OPTIONS = [
  { value: 'Haute', color: 'dark-red' },
  { value: 'Normale', color: 'dark-blue' },
  { value: 'Basse', color: 'dark-gray' },
] as const;

export const NOTE_TYPE_OPTIONS = [
  { value: 'RDV', color: 'dark-blue' },
  { value: 'Appel', color: 'dark-green' },
  { value: 'Email', color: 'dark-purple' },
  { value: 'Document', color: 'dark-orange' },
  { value: 'Reporting', color: 'dark-blue' },
  { value: 'Formation', color: 'dark-green' },
  { value: 'Réclamation', color: 'dark-red' },
  { value: 'Note interne', color: 'dark-gray' },
  { value: 'Autre', color: 'dark-gray' },
] as const;

export const GESTIONNAIRE_STATUS_OPTIONS = [
  { value: 'Actif', color: 'dark-green' },
  { value: 'Inactif', color: 'dark-gray' },
] as const;

export const FCC_DOSSIER_STATUS_OPTIONS = [
  { value: 'En attente', color: 'dark-gray' },
  { value: 'En review', color: 'dark-blue' },
  { value: 'Validé', color: 'dark-green' },
  { value: 'Envoyé DocuSign', color: 'dark-cyan' },
  { value: 'Signé', color: 'dark-green' },
  { value: 'Incomplet', color: 'dark-orange' },
  { value: 'Archivé', color: 'dark-gray' },
  { value: 'Rejeté', color: 'dark-red' },
] as const;
